version: '3.9'

services:
  data_service:
    image: data_service
    build: .
    command: npm run start
    depends_on:
      - db
    ports:
      - '8080:8080'
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "default_user"
      POSTGRES_PASSWORD: "pswrd"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"